# Generated by Django 4.2.20 on 2025-04-26 01:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServerRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fqdn', models.CharField(help_text='Fully Qualified Domain Name (e.g., server1.example.com)', max_length=255, unique=True)),
                ('vlan', models.CharField(help_text='VLAN ID or Name', max_length=100)),
                ('site', models.CharField(help_text='Datacenter or Site Location', max_length=100)),
                ('primary_contact', models.CharField(help_text='Primary Contact Person/Email/Group', max_length=255)),
                ('secondary_contact', models.CharField(blank=True, help_text='Secondary Contact (Optional)', max_length=255)),
                ('group_contact', models.CharField(blank=True, help_text='Group Contact / DL (Optional)', max_length=255)),
                ('notes', models.TextField(blank=True, help_text='Any additional notes or requirements')),
                ('backup_required', models.BooleanField(default=False)),
                ('monitoring_required', models.BooleanField(default=False)),
                ('asap_number', models.CharField(blank=True, help_text='ASAP/Remedy/ServiceNow Ticket Number (Optional)', max_length=100)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved - Queued for Provisioning'), ('DENIED', 'Denied'), ('PROVISIONING', 'Provisioning in Progress'), ('COMPLETED', 'Provisioning Completed'), ('FAILED', 'Provisioning Failed')], default='PENDING', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_denied_at', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes for IT Admins')),
                ('awx_job_id', models.IntegerField(blank=True, help_text='ID of the launched AWX Job', null=True)),
                ('approved_denied_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Server Request',
                'verbose_name_plural': 'Server Requests',
                'ordering': ['-requested_at'],
            },
        ),
    ]
#