# Generated by Django 4.2.20 on 2025-04-26 01:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('requests_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('level', models.CharField(choices=[('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('SUCCESS', 'Success')], default='INFO', max_length=10)),
                ('action', models.CharField(help_text='Short description of the action performed.', max_length=255)),
                ('message', models.TextField(help_text='Detailed log message.')),
                ('related_awx_job_id', models.IntegerField(blank=True, help_text='AWX Job ID related to this log entry (if applicable).', null=True)),
                ('related_request', models.ForeignKey(blank=True, help_text='The server request this log pertains to (if applicable).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='requests_app.serverrequest')),
                ('user', models.ForeignKey(blank=True, help_text='User who performed the action (if applicable).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log Entry',
                'verbose_name_plural': 'Audit Log Entries',
                'ordering': ['-timestamp'],
            },
        ),
    ]
#