# Generated by Django 4.2.20 on 2025-04-26 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests_app', '0002_auditlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serverrequest',
            name='primary_contact',
            field=models.EmailField(help_text='Primary Contact Email Address', max_length=255),
        ),
        migrations.AlterField(
            model_name='serverrequest',
            name='secondary_contact',
            field=models.CharField(blank=True, help_text='Secondary Contact Email Address', max_length=255),
        ),
    ]
